on: 
  push: 
    tags: 
      - v*
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
      working-directory: src
    - name: Release
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: src/juanipc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
